---
- hosts: all
  vars_files:
    - vars/main.yml

  tasks:
  
  - name: Copiar configuración de seguridad de tomcat
      copy:
        src: /root/ansible/tomcat-centos/resources/tomcat-users.xml
        dest: "{{directorio_inst}}/conf"
        owner: "{{usuario_servicio}}"
        group: "{{grupo_servicio}}"

    - name: Habilitando usuario
      systemd:
        name: tomcat.service
        state: stopped

    - name: Iniciando
      systemd:
        name: tomcat.service
        state: started
